### ISSUE TITLE
Consider non-standard feature. Re-purpose useless %n to print a string then free it from the heap

### ISSUE THREAD

**Issue by mickjc750** [mickjc750/prnf#1]
When attempting to print strings generated by application specific functions, there are some difficulties...

For example, consider a function which takes an integer 'seconds' and describes the duration as xxDxxHxxMxxS.

>__char* period2txt(char* buf, int seconds);__

If this function is used for multiple arguments to a single prnf(), a separate buffer must be provided for each call, eg.

>__char buf1[20];__
>__char buf2[20];__
>__prnf("Fred is %s, Bob is %s\n", period2txt(buf1, freds_age), period2txt(buf2, bobs_age));__

The above is ugly and error prone. Accidentally put buf1 in both, and it breaks. Undersize the buffer and it breaks.

### Proposed solution

The standard printf() provides __%n__, which is normally used to write the number of characters printed so far, to an integer pointed to by the argument. I cannot think of a practical application of this, and I don't know why it exists.
 As __%n__ expects a pointer (int*) as an argument, this could actually point to a string in a heap allocation. prnf() could then free the allocation after printing it. 
 If our function period2txt() makes a heap allocation when buf is passed as NULL, then we could do this:

prnf("Fred is %n, Bob is %n\n", (int*)period2txt(NULL, freds_age), (int*)period2txt(NULL, bobs_age));

Or, if period2txt is __only__ to be used as a prnf argument, it could be of the form:

>__int* prnf_n_period(int seconds);__

This would allow usage as simple as:

>__prnf("Fred is %n, Bob is %n\n", prnf_n_period(freds_age), prnf_n_period(bobs_age));__

There are some benefits to this.
1. Mixing up %s and %n will give you a compilation warning, as %s expects (char*) and %n expects(int*)
2. Misuse of prnf_n_period() for other purposes, such as using it in an assignment to a char* will also cause a compilation warning due to pointer types.

Unfortunately the compilers format checking will complain if we try to specify width or precision for %n. So no alignment by prnf for %n strings would be possible.

If anyone is out there.. please share your thoughts on this.

**Comment by mickjc750** [comment]
As nobody is really following or watching, I just did it.

**Comment by mickjc750** [comment]
** BEWARE **
If you are writing your own variadic function which directly calls vsnprnf(NULL, 0, fmt, va) for the purpose of measuring the length of the output, and then vsprnf() to actually print the output, a double free will occur on any %n argument, as you are effectively printing twice.

**Comment by eyalroz** [comment]
> I cannot think of a practical application of this, and I don't know why it exists.

Why can't you? Are you saying people should just always break their `printf()` calls into multiple calls and use the return value? You could make that claim, but then - why have `printf()` at all, when you could just have functions for each of the format specifiers supported?

> prnf() could then free the allocation after printing it.

A bit convoluted, but I suppose it could be useful in the scenario you described. 

> prnf("Fred is %n, Bob is %n\n", (int*)period2txt(NULL, freds_age), (int*)period2txt(NULL, bobs_age));

No no no, very confusing, bad idea. And why must you cannibalize `%n`? There are plenty of unused letters you could take instead.

> Or, if period2txt is only to be used as a prnf argument, it could be of the form:

    int* prnf_n_period(int seconds);

This is is silly. And who's to say `period2txt()` isn't used elsewhere?

What you should probably do is have `%S` behave like `%s`, but free the argument after use. Simple and reasonable.

**Comment by mickjc750** [comment]
> Why can't you? Are you saying people should just always break their printf() calls into multiple calls and use the return value?

Have you ever used %n? what for? If text alignment is needed, it's normally done to a fixed position using the width specifier.
Why would you want to know the position of some variable mid-point in the string?

> why have printf() at all, when you could just have functions for each of the format specifiers supported?

I actually did this for years. It turns into a hell of a lot of function calls, and a lot of typing. Also there are different modes of output to accommodate. So I had ascii_int32() for writing to char buffers, and then ascii_fifo_int32() for writing to streams.
 By using a function as an argument for printf() you can then use the same function with snprintf() fptrprnf() etc..

> No no no, very confusing, bad idea. And why must you cannibalize %n? There are plenty of unused letters you could take instead.

Unused letters will produce the compilation warning "unknown type specifier %". I want to make use of the compilers format+argument checking. The only other type which takes a pointer is %p, but I may want to implement %p to display a pointer in the future. 

> More confusion... and who's to say period2txt() isn't used elsewhere?

Well the author of prnf_n_period() would document this as being specifically for the purpose of providing arguments to prnf().
If someone were to misuse it in an assignment to a char*, this would produce a compilation warning (due to different pointer types). If there already exists a period2txt(), then prnf_n_period() could be a simple wrapper to return the result as an int*
I agree it is confusing to see a function prototype returning an int* though, especially when it produces text.

> What you should probably do is have %S behave like %s, but free the argument after use. Simple and reasonable.

This would have been a better option. But unfortunately %S has already been cannibalized. On AVR it means to read the string from program memory instead of ram.

**Comment by eyalroz** [comment]
> Unused letters will produce the compilation warning "unknown type specifier %". I want to make use of the compilers format+argument checking. The only other type which takes a pointer is %p, but I may want to implement %p to display a pointer in the future.

Well, it shouldn't necessary print a warning; or one could disable the warning - but it's better to have it than to expose a printf()-like functions with different semantics for an existing specifier.

> %S has already been cannibalized. On AVR it means to read the string from program memory instead of ram.

So you're already getting a warning about it?

Anyway, I still believe you should an unused specifier, not %n.

**Comment by mickjc750** [comment]
Thanks for your input Eyaloz. I understand the danger now.

On one hand, I have the irritation of warnings.
On the other hand, I have the danger of someone expecting %n to work like the printf %n.

 I can document it. And they will have to read the documentation to enable the feature in the first place. But then a future programmer working on the project may think "Hey I wonder if this prnf thing has %n?", try it out, compile without warning, then crash.... It may be a painful thing to diagnose.

 If I were to use %h instead of %n, I would still like to avoid using (char*) for the argument type. The reason being that it's too easy to accidentally use %s instead of %h, and then a memory leak will occur. I'm 100% certain that I will make this mistake myself.

 Alternatively, if I do stick with %n, I think I should at least produce a compiler warning alerting the developer to the differences between prnf and printf. At least that way I can have a single warning, instead of a warning for every instance of %h
